# Indentation
tabWidth: 2
useTabs: false

# Word wrap
printWidth: 120

# Line endings
semi: true
trailingComma: all
endOfLine: lf

# Brackets
bracketSameLine: false
bracketSpacing: true

# Parentheses
arrowParens: always

# Quotation
singleQuote: true
quoteProps: as-needed
